import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // {type: 'autogenerated', dirName: '.'},
    'intro',

    // Item 2: A category for your "Basics" tutorial.
    // Docusaurus will use the `tutorial-basics/_category_.json` file for its label.
    {
      type: 'category',
      label: 'Tutorial - Basics',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-basics',
        },
      ],
    },

    // Item 3: A category for your "Extras" tutorial.
    {
      type: 'category',
      label: 'Tutorial - Extras',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorial-extras',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description: 'This is the auto-generated API reference for dagster-slurm, created from Python docstrings.',
        slug: '/category/api-reference'
      },
      // This tells Docusaurus to automatically generate sidebar items
      // from the markdown files inside the 'docs/docs/api' directory.
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
