import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // {type: 'autogenerated', dirName: '.'},
    'intro',

    {
      type: 'category',
      label: 'How-to guides',
      collapsible: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'how-to',
        },
      ],
    },

    {
      type: 'category',
      label: 'Ray integration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'integration-ray',
        },
      ],
    },

    {
      type: 'category',
      label: 'Spark integration',
      items: [
        {
          type: 'autogenerated',
          dirName: 'integration-spark',
        },
      ],
    },

    {
      type: 'category',
      label: 'Contributing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'contributing',
        },
      ],
    },
    'slides',
    {
      type: 'category',
      label: 'API Reference',
      items: [{type: 'autogenerated', dirName: 'api'}],
    },
  ],
};

export default sidebars;
