name: slides and pdf render

on:
  push:
    branches: [main]
    paths:
      - "slides/**"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "slides/**"
  workflow_dispatch:

concurrency:
  group: slides-main-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build slides and render PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7.0.0

      - name: Install Nix
        uses: cachix/install-nix-action@v31.11.0

      - name: Enable Cachix
        uses: cachix/cachix-action@v17
        with:
          name: devenv

      - name: Install devenv
        run: nix profile install github:cachix/devenv/v2.1.2

      # - run: pixi run -e docs --frozen slides-build
      - run: devenv shell -- pixi run -e docs --frozen slides-export-pdf
      - run: devenv shell -- pixi run -e docs --frozen slides-export-pdf-multimodal
      - run: devenv shell -- pixi run -e docs --frozen slides-export-pdf-scipy2026

      - name: Upload hackathon PDF
        uses: actions/upload-artifact@v7.0.1
        with:
          name: slides-hackathon
          path: slides/slides-export.pdf
          retention-days: 5

      - name: Upload multimodal PDF
        uses: actions/upload-artifact@v7.0.1
        with:
          name: slides-multimodal
          path: slides/slides_multimodal-export.pdf
          retention-days: 5

      - name: Upload SciPy 2026 PDF
        uses: actions/upload-artifact@v7.0.1
        with:
          name: slides-scipy2026
          path: slides/slides_scipy2026-export.pdf
          retention-days: 5
